### ISSUE TITLE
No RDP port set

### ISSUE THREAD

**Issue by dhmistry3** [ecalder6/azure-gaming#21]
I wasn't able to connect with remote desktop.  On closer inspection it doesn't look like port 3389 is set in the NAT incoming settings.

**Comment by ecalder6** [comment]
Just tried it and RDP worked for me. Check if you have a network security group under the network interface, CloudGamingNic. There shouldn't be one.

**Comment by fanoush** [comment]
It is not setup for low priority/scaleset, the LowPri.json template has 
>        "natStartPort": 50000,
>        "natEndPort": 50120,
>        "natBackendPort": 22,

which is ssh port. Also the " Log into your VM" guide doesn't tell to use port 50000.

Anyway, this is working beautifully for me now, thank you. I used RDP directly over ZeroTier network private IP so the public access was not needed. Also Steam streaming didn't work for me at first and computers didn't see each other in Steam (despite ping and remote desktop working) but later it started to work - not sure if it is because I switched ZeroTier network to private after both machines connected and enabled broadcast on the network in ZeroTier. Also I had to reboot the VM after installing games in Steam, at first it didn't detect nvidia video and games were very slow or refused to start due to missing 3d acceleration.
